DROP TABLE IF EXISTS MOVIES;
 
CREATE TABLE MOVIES (
ID INT AUTO_INCREMENT  PRIMARY KEY,
NAME VARCHAR(250),
DIRECTOR VARCHAR(250),
HERO VARCHAR(250),
HEROINE VARCHAR(250),
LANGUAGE VARCHAR(250));

INSERT INTO MOVIES (NAME, DIRECTOR, HERO, HEROINE, LANGUAGE) VALUES ('Kabir Singh', 'Sandeep', 'Shahid Kapoor', 'Kiara Advani', 'Hindi');
INSERT INTO MOVIES (NAME, DIRECTOR, HERO, HEROINE, LANGUAGE) VALUES ('Arjun Reddy', 'Sandeep', 'Vijay', 'Shalini', 'Telugu');
INSERT INTO MOVIES (NAME, DIRECTOR, HERO, HEROINE, LANGUAGE) VALUES ('Pelli Choopulu', 'Tharun', 'Vijay', 'Ritu Varma', 'Telugu');
INSERT INTO MOVIES (NAME, DIRECTOR, HERO, HEROINE, LANGUAGE) VALUES ('Ee Nagaraniki Emainid', 'Tharun', 'Vishwaksen', 'Anisha', 'Telugu');